apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
data:
  git-repo-url: git@github.com:vitech-team/mood-feed-test.git
  container-image: gcr.io/sdlc-286111/mood-feed-test
