apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
data:
  git-repo-url: {{ .Values.git.url }}
  imageName: {{ .Values.image.name }}
  imageTag: {{ .Values.image.tag }}
  image: {{ .Values.image.name }}:{{ .Values.image.tag }}
